# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  - name: payload
    value: "initial value"

steps:
- task: PythonScript@0
  displayName: 'install requests latest requests library'
  inputs:
    scriptSource: 'inline'
    script: |
      import sys
      import subprocess
      
      # implement pip as a subprocess:
      subprocess.check_call([sys.executable, '-m', 'pip', 'install', 
      'requests'])

- task: PythonScript@0
  displayName: 'Get file from Github and set variable'
  inputs:
    scriptSource: 'inline'
    script: |
      import requests as req
      
      #raw file url
      url='https://raw.githubusercontent.com/fakemail1865/SemarchyModel/main/testnew%20%5B0.0%5D.xml'
      
      with req.get(url) as rq:
          payload = rq.content
      
      payload = payload.decode()
      
      print ('##vso[task.setvariable variable=payload;isoutput=true]' + payload)

- task: PythonScript@0
  displayName: 'Print payload variable'
  inputs:
    scriptSource: 'inline'
    script: 'print($(payload))'
